# Generated by Django 3.0.6 on 2020-05-15 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Length has to be 16', regex='^.{16}$')])),
                ('card_cvc', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Length has to be 3', regex='^.{3}$')])),
                ('card_expire_year', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Length has to be 2', regex='^.{2}$')])),
                ('card_expire_month', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Length has to be 2', regex='^.{2}$')])),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('house_number', models.IntegerField(max_length=4)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(max_length=4)),
            ],
        ),
    ]
