# Generated by Django 3.0.6 on 2020-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(max_length=4),
        ),
    ]
