# Generated by Django 3.0.6 on 2020-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoles',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='consoles',
            name='logo',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
