# Generated by Django 3.0.6 on 2020-05-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0002_auto_20200505_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consoles',
            old_name='logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='consoles',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
