# Generated by Django 3.0.6 on 2020-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0003_auto_20200505_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoles',
            name='name',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
