# Generated by Django 3.0.6 on 2020-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_auto_20200505_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoles',
            name='image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
