# Generated by Django 3.0.6 on 2020-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0007_auto_20200505_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoles',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
