# Generated by Django 3.0.6 on 2020-05-14 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0008_auto_20200505_1436'),
        ('games', '0006_auto_20200513_1808'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('console', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
