# Generated by Django 3.0.6 on 2020-05-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200513_1808'),
        ('consoles', '0008_auto_20200505_1436'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
