# Generated by Django 3.0.6 on 2020-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0008_auto_20200505_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999)),
                ('image', models.CharField(blank=True, max_length=999)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=99999)),
                ('price', models.FloatField(blank=True)),
                ('console', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
            ],
        ),
    ]
