# Generated by Django 3.0.6 on 2020-05-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0002_auto_20200505_1223'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='console',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles'),
        ),
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
