# Generated by Django 3.0.6 on 2020-05-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0008_auto_20200505_1436'),
        ('games', '0003_auto_20200505_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
